services:
  db-clients:
    container_name: db-clients
    image: postgres:latest
    env_file:
      - ../gestionClient/.env
    volumes:
      - db-clients-data:/var/lib/postgresql/data
    networks:
      - payetonkawa-n

  gestion-client:
    container_name: gestion-client
    build:
      context: ../gestionClient
      dockerfile: Dockerfile
    env_file:
      - ../gestionClient/.env
    ports:
      - '8082:8080'
    depends_on:
      - db-clients
    networks:
      - payetonkawa-n

volumes:
  db-clients-data:

networks:
  payetonkawa-n:
    external: true
